# Generated by Django 5.2.14 on 2026-05-11 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorEarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('source_type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsor_earnings_records', to=settings.AUTH_USER_MODEL)),
                ('sponsored_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_sponsor_earnings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
