# Generated by Django 5.2.3 on 2026-05-11 14:53

from django.db import migrations, models


def populate_unique_ids(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    for user in User.objects.all().order_by('id'):
        if not user.unique_id:
            user.unique_id = f"24TX-{user.id:06d}"
            user.save(update_fields=['unique_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='unique_id',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.RunPython(populate_unique_ids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='unique_id',
            field=models.CharField(blank=True, db_index=True, max_length=20, unique=True),
        ),
    ]
