# Generated by Django 5.2.14 on 2026-05-11 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage1_hours', models.IntegerField(default=72)),
                ('stage1_percent', models.DecimalField(decimal_places=2, default=50, max_digits=5)),
                ('stage2_hours', models.IntegerField(default=24)),
                ('stage2_percent', models.DecimalField(decimal_places=2, default=25, max_digits=5)),
                ('stage3_hours', models.IntegerField(default=24)),
                ('stage3_percent', models.DecimalField(decimal_places=2, default=25, max_digits=5)),
                ('min_purchase', models.DecimalField(decimal_places=8, default=10, max_digits=20)),
                ('max_purchase', models.DecimalField(decimal_places=8, default=100000, max_digits=20)),
                ('usdt_wallet_address', models.CharField(default='0x0000000000000000000000000000000000000000', max_length=255)),
                ('sponsor_percentage', models.DecimalField(decimal_places=2, default=5, max_digits=5)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
