# Generated by Django 5.2.3 on 2026-05-11 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='coin_rate',
            field=models.DecimalField(decimal_places=8, default=0.25, help_text='Price of one coin in USD. Example: 0.25 means 1 Coin = $0.25', max_digits=20),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='currency_symbol',
            field=models.CharField(default='USD', help_text='Currency symbol (e.g., USD, EUR)', max_length=10),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='last_updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Last time coin rate was updated'),
        ),
    ]
