# Generated by Django 6.0.5 on 2026-05-11 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0002_systemsettings_coin_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='sold_coins',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='total_coin_supply',
            field=models.DecimalField(decimal_places=8, default=21000000, max_digits=30),
        ),
    ]
