# Generated by Django 5.2.3 on 2026-05-14 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_purchase_approved_coin_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='rejection_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='rejection_notes',
            field=models.TextField(blank=True, help_text='Additional notes from admin', null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='rejection_reason_type',
            field=models.CharField(blank=True, choices=[('transaction_id_mismatch', 'Transaction ID not matching'), ('wallet_address_invalid', 'Wallet address invalid or incomplete'), ('amount_mismatch', 'Amount does not match'), ('screenshot_invalid', 'Screenshot unclear or invalid'), ('duplicate_transaction', 'Duplicate transaction detected'), ('suspicious_activity', 'Suspicious activity detected'), ('incomplete_payment', 'Payment not received or incomplete'), ('other', 'Other reason')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='PurchaseRejectionDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='rejection_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rejection_documents', to='purchases.purchase')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
